name: Find Secrets
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: max/secret-scan@master
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: secret-scan-reports
          path: reports
